/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 83
#define ALIAS_COUNT 0
#define TOKEN_COUNT 72
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_if = 3,
  anon_sym_elif = 4,
  anon_sym_else = 5,
  anon_sym_while = 6,
  anon_sym_for = 7,
  anon_sym_in = 8,
  anon_sym_break = 9,
  anon_sym_continue = 10,
  anon_sym_with = 11,
  anon_sym_as = 12,
  anon_sym_try = 13,
  anon_sym_except = 14,
  anon_sym_finally = 15,
  anon_sym_local = 16,
  anon_sym_global = 17,
  anon_sym_import = 18,
  anon_sym_from = 19,
  anon_sym_fn = 20,
  anon_sym_return = 21,
  anon_sym_del = 22,
  sym_keyword_exception = 23,
  anon_sym_and = 24,
  anon_sym_or = 25,
  anon_sym_not = 26,
  anon_sym_has = 27,
  anon_sym_print = 28,
  anon_sym_gc = 29,
  sym_decorator = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  sym_nil = 33,
  anon_sym_setmetatable = 34,
  anon_sym_getmetatable = 35,
  anon_sym_str = 36,
  anon_sym_len = 37,
  anon_sym_type = 38,
  anon_sym_assert = 39,
  anon_sym_error = 40,
  sym_number = 41,
  sym_string = 42,
  sym_multiline_string = 43,
  sym_fstring = 44,
  anon_sym_EQ_EQ = 45,
  anon_sym_BANG_EQ = 46,
  anon_sym_LT_EQ = 47,
  anon_sym_GT_EQ = 48,
  anon_sym_DOT_DOT = 49,
  anon_sym_STAR_STAR = 50,
  anon_sym_SLASH_SLASH = 51,
  anon_sym_EQ = 52,
  anon_sym_LT = 53,
  anon_sym_GT = 54,
  anon_sym_PLUS = 55,
  anon_sym_DASH = 56,
  anon_sym_STAR = 57,
  anon_sym_SLASH = 58,
  anon_sym_PERCENT = 59,
  anon_sym_POUND = 60,
  anon_sym_QMARK = 61,
  anon_sym_LPAREN = 62,
  anon_sym_RPAREN = 63,
  anon_sym_LBRACE = 64,
  anon_sym_RBRACE = 65,
  anon_sym_LBRACK = 66,
  anon_sym_RBRACK = 67,
  anon_sym_COMMA = 68,
  anon_sym_DOT = 69,
  anon_sym_SEMI = 70,
  anon_sym_COLON = 71,
  sym_source_file = 72,
  sym_keyword_control = 73,
  sym_keyword_declaration = 74,
  sym_keyword_operator = 75,
  sym_keyword_other = 76,
  sym_boolean = 77,
  sym_builtin = 78,
  sym_operator = 79,
  sym_punctuation_bracket = 80,
  sym_punctuation_delimiter = 81,
  aux_sym_source_file_repeat1 = 82,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_with] = "with",
  [anon_sym_as] = "as",
  [anon_sym_try] = "try",
  [anon_sym_except] = "except",
  [anon_sym_finally] = "finally",
  [anon_sym_local] = "local",
  [anon_sym_global] = "global",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [anon_sym_fn] = "fn",
  [anon_sym_return] = "return",
  [anon_sym_del] = "del",
  [sym_keyword_exception] = "keyword_exception",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_not] = "not",
  [anon_sym_has] = "has",
  [anon_sym_print] = "print",
  [anon_sym_gc] = "gc",
  [sym_decorator] = "decorator",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_setmetatable] = "setmetatable",
  [anon_sym_getmetatable] = "getmetatable",
  [anon_sym_str] = "str",
  [anon_sym_len] = "len",
  [anon_sym_type] = "type",
  [anon_sym_assert] = "assert",
  [anon_sym_error] = "error",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_multiline_string] = "multiline_string",
  [sym_fstring] = "fstring",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_POUND] = "#",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym_keyword_control] = "keyword_control",
  [sym_keyword_declaration] = "keyword_declaration",
  [sym_keyword_operator] = "keyword_operator",
  [sym_keyword_other] = "keyword_other",
  [sym_boolean] = "boolean",
  [sym_builtin] = "builtin",
  [sym_operator] = "operator",
  [sym_punctuation_bracket] = "punctuation_bracket",
  [sym_punctuation_delimiter] = "punctuation_delimiter",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_try] = anon_sym_try,
  [anon_sym_except] = anon_sym_except,
  [anon_sym_finally] = anon_sym_finally,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_del] = anon_sym_del,
  [sym_keyword_exception] = sym_keyword_exception,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_has] = anon_sym_has,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_gc] = anon_sym_gc,
  [sym_decorator] = sym_decorator,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_setmetatable] = anon_sym_setmetatable,
  [anon_sym_getmetatable] = anon_sym_getmetatable,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_len] = anon_sym_len,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_error] = anon_sym_error,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_multiline_string] = sym_multiline_string,
  [sym_fstring] = sym_fstring,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym_keyword_control] = sym_keyword_control,
  [sym_keyword_declaration] = sym_keyword_declaration,
  [sym_keyword_operator] = sym_keyword_operator,
  [sym_keyword_other] = sym_keyword_other,
  [sym_boolean] = sym_boolean,
  [sym_builtin] = sym_builtin,
  [sym_operator] = sym_operator,
  [sym_punctuation_bracket] = sym_punctuation_bracket,
  [sym_punctuation_delimiter] = sym_punctuation_delimiter,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_try] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_except] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_finally] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_del] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword_exception] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_has] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gc] = {
    .visible = true,
    .named = false,
  },
  [sym_decorator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_setmetatable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_getmetatable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_len] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [sym_fstring] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_control] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_other] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation_delimiter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 6,
        '"', 1,
        '#', 43,
        '%', 42,
        '\'', 3,
        '(', 45,
        ')', 46,
        '*', 40,
        '+', 38,
        ',', 51,
        '-', 39,
        '.', 52,
        '/', 41,
        ':', 54,
        ';', 53,
        '<', 36,
        '=', 35,
        '>', 37,
        '?', 44,
        '@', 5,
        '[', 49,
        ']', 50,
        'f', 20,
        '{', 47,
        '}', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(26);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_decorator);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_multiline_string);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_fstring);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(18);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(33);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(9);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(32);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'g', 7,
        'h', 8,
        'i', 9,
        'l', 10,
        'n', 11,
        'o', 12,
        'p', 13,
        'r', 14,
        's', 15,
        't', 16,
        'w', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 'r') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == 'o') ADVANCE(29);
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(35);
      if (lookahead == 'm') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(40);
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(47);
      if (lookahead == 'r') ADVANCE(48);
      if (lookahead == 'y') ADVANCE(49);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(50);
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(52);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_gc);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(66);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 36:
      if (lookahead == 'p') ADVANCE(68);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(70);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(78);
      if (lookahead == 'y') ADVANCE(79);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(80);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 54:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_del);
      END_STATE();
    case 57:
      if (lookahead == 'f') ADVANCE(86);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(88);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(90);
      END_STATE();
    case 62:
      if (lookahead == 'a') ADVANCE(91);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 64:
      if (lookahead == 'm') ADVANCE(92);
      END_STATE();
    case 65:
      if (lookahead == 'm') ADVANCE(93);
      END_STATE();
    case 66:
      if (lookahead == 'b') ADVANCE(94);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_has);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_len);
      END_STATE();
    case 70:
      if (lookahead == 'a') ADVANCE(96);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 74:
      if (lookahead == 'u') ADVANCE(98);
      END_STATE();
    case 75:
      if (lookahead == 'm') ADVANCE(99);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 77:
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_try);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(103);
      END_STATE();
    case 82:
      if (lookahead == 'h') ADVANCE(104);
      END_STATE();
    case 83:
      if (lookahead == 'r') ADVANCE(105);
      END_STATE();
    case 84:
      if (lookahead == 'k') ADVANCE(106);
      END_STATE();
    case 85:
      if (lookahead == 'i') ADVANCE(107);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 88:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 89:
      if (lookahead == 'p') ADVANCE(109);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 91:
      if (lookahead == 'l') ADVANCE(111);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 93:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 94:
      if (lookahead == 'a') ADVANCE(113);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(114);
      END_STATE();
    case 96:
      if (lookahead == 'l') ADVANCE(115);
      END_STATE();
    case 97:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(117);
      END_STATE();
    case 99:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 100:
      if (lookahead == 'w') ADVANCE(119);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 103:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(121);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 107:
      if (lookahead == 'n') ADVANCE(122);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_error);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(123);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 111:
      if (lookahead == 'l') ADVANCE(124);
      END_STATE();
    case 112:
      if (lookahead == 't') ADVANCE(125);
      END_STATE();
    case 113:
      if (lookahead == 'l') ADVANCE(126);
      END_STATE();
    case 114:
      if (lookahead == 't') ADVANCE(127);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 117:
      if (lookahead == 'n') ADVANCE(128);
      END_STATE();
    case 118:
      if (lookahead == 't') ADVANCE(129);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_keyword_exception);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 122:
      if (lookahead == 'u') ADVANCE(130);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_except);
      END_STATE();
    case 124:
      if (lookahead == 'y') ADVANCE(131);
      END_STATE();
    case 125:
      if (lookahead == 'a') ADVANCE(132);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 129:
      if (lookahead == 'a') ADVANCE(133);
      END_STATE();
    case 130:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_finally);
      END_STATE();
    case 132:
      if (lookahead == 't') ADVANCE(135);
      END_STATE();
    case 133:
      if (lookahead == 't') ADVANCE(136);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 135:
      if (lookahead == 'a') ADVANCE(137);
      END_STATE();
    case 136:
      if (lookahead == 'a') ADVANCE(138);
      END_STATE();
    case 137:
      if (lookahead == 'b') ADVANCE(139);
      END_STATE();
    case 138:
      if (lookahead == 'b') ADVANCE(140);
      END_STATE();
    case 139:
      if (lookahead == 'l') ADVANCE(141);
      END_STATE();
    case 140:
      if (lookahead == 'l') ADVANCE(142);
      END_STATE();
    case 141:
      if (lookahead == 'e') ADVANCE(143);
      END_STATE();
    case 142:
      if (lookahead == 'e') ADVANCE(144);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_getmetatable);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_setmetatable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_try] = ACTIONS(1),
    [anon_sym_except] = ACTIONS(1),
    [anon_sym_finally] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_del] = ACTIONS(1),
    [sym_keyword_exception] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_has] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_gc] = ACTIONS(1),
    [sym_decorator] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_setmetatable] = ACTIONS(1),
    [anon_sym_getmetatable] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_len] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_error] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_multiline_string] = ACTIONS(1),
    [sym_fstring] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym_keyword_control] = STATE(2),
    [sym_keyword_declaration] = STATE(2),
    [sym_keyword_operator] = STATE(2),
    [sym_keyword_other] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_builtin] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_punctuation_bracket] = STATE(2),
    [sym_punctuation_delimiter] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_elif] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_in] = ACTIONS(11),
    [anon_sym_break] = ACTIONS(11),
    [anon_sym_continue] = ACTIONS(11),
    [anon_sym_with] = ACTIONS(11),
    [anon_sym_as] = ACTIONS(11),
    [anon_sym_try] = ACTIONS(11),
    [anon_sym_except] = ACTIONS(11),
    [anon_sym_finally] = ACTIONS(11),
    [anon_sym_local] = ACTIONS(13),
    [anon_sym_global] = ACTIONS(13),
    [anon_sym_import] = ACTIONS(13),
    [anon_sym_from] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(13),
    [anon_sym_del] = ACTIONS(13),
    [sym_keyword_exception] = ACTIONS(7),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_has] = ACTIONS(15),
    [anon_sym_print] = ACTIONS(17),
    [anon_sym_gc] = ACTIONS(17),
    [sym_decorator] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(7),
    [anon_sym_setmetatable] = ACTIONS(21),
    [anon_sym_getmetatable] = ACTIONS(21),
    [anon_sym_str] = ACTIONS(21),
    [anon_sym_len] = ACTIONS(21),
    [anon_sym_type] = ACTIONS(21),
    [anon_sym_assert] = ACTIONS(21),
    [anon_sym_error] = ACTIONS(21),
    [sym_number] = ACTIONS(9),
    [sym_string] = ACTIONS(9),
    [sym_multiline_string] = ACTIONS(9),
    [sym_fstring] = ACTIONS(9),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [anon_sym_STAR_STAR] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_QMARK] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_COLON] = ACTIONS(31),
  },
  [STATE(2)] = {
    [sym_keyword_control] = STATE(3),
    [sym_keyword_declaration] = STATE(3),
    [sym_keyword_operator] = STATE(3),
    [sym_keyword_other] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_builtin] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation_bracket] = STATE(3),
    [sym_punctuation_delimiter] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [sym_comment] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_elif] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_in] = ACTIONS(11),
    [anon_sym_break] = ACTIONS(11),
    [anon_sym_continue] = ACTIONS(11),
    [anon_sym_with] = ACTIONS(11),
    [anon_sym_as] = ACTIONS(11),
    [anon_sym_try] = ACTIONS(11),
    [anon_sym_except] = ACTIONS(11),
    [anon_sym_finally] = ACTIONS(11),
    [anon_sym_local] = ACTIONS(13),
    [anon_sym_global] = ACTIONS(13),
    [anon_sym_import] = ACTIONS(13),
    [anon_sym_from] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(13),
    [anon_sym_del] = ACTIONS(13),
    [sym_keyword_exception] = ACTIONS(37),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_has] = ACTIONS(15),
    [anon_sym_print] = ACTIONS(17),
    [anon_sym_gc] = ACTIONS(17),
    [sym_decorator] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(37),
    [anon_sym_setmetatable] = ACTIONS(21),
    [anon_sym_getmetatable] = ACTIONS(21),
    [anon_sym_str] = ACTIONS(21),
    [anon_sym_len] = ACTIONS(21),
    [anon_sym_type] = ACTIONS(21),
    [anon_sym_assert] = ACTIONS(21),
    [anon_sym_error] = ACTIONS(21),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_multiline_string] = ACTIONS(39),
    [sym_fstring] = ACTIONS(39),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [anon_sym_STAR_STAR] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_QMARK] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_COLON] = ACTIONS(31),
  },
  [STATE(3)] = {
    [sym_keyword_control] = STATE(3),
    [sym_keyword_declaration] = STATE(3),
    [sym_keyword_operator] = STATE(3),
    [sym_keyword_other] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_builtin] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation_bracket] = STATE(3),
    [sym_punctuation_delimiter] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_identifier] = ACTIONS(43),
    [sym_comment] = ACTIONS(46),
    [anon_sym_if] = ACTIONS(49),
    [anon_sym_elif] = ACTIONS(49),
    [anon_sym_else] = ACTIONS(49),
    [anon_sym_while] = ACTIONS(49),
    [anon_sym_for] = ACTIONS(49),
    [anon_sym_in] = ACTIONS(49),
    [anon_sym_break] = ACTIONS(49),
    [anon_sym_continue] = ACTIONS(49),
    [anon_sym_with] = ACTIONS(49),
    [anon_sym_as] = ACTIONS(49),
    [anon_sym_try] = ACTIONS(49),
    [anon_sym_except] = ACTIONS(49),
    [anon_sym_finally] = ACTIONS(49),
    [anon_sym_local] = ACTIONS(52),
    [anon_sym_global] = ACTIONS(52),
    [anon_sym_import] = ACTIONS(52),
    [anon_sym_from] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(52),
    [anon_sym_return] = ACTIONS(52),
    [anon_sym_del] = ACTIONS(52),
    [sym_keyword_exception] = ACTIONS(43),
    [anon_sym_and] = ACTIONS(55),
    [anon_sym_or] = ACTIONS(55),
    [anon_sym_not] = ACTIONS(55),
    [anon_sym_has] = ACTIONS(55),
    [anon_sym_print] = ACTIONS(58),
    [anon_sym_gc] = ACTIONS(58),
    [sym_decorator] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(61),
    [anon_sym_false] = ACTIONS(61),
    [sym_nil] = ACTIONS(43),
    [anon_sym_setmetatable] = ACTIONS(64),
    [anon_sym_getmetatable] = ACTIONS(64),
    [anon_sym_str] = ACTIONS(64),
    [anon_sym_len] = ACTIONS(64),
    [anon_sym_type] = ACTIONS(64),
    [anon_sym_assert] = ACTIONS(64),
    [anon_sym_error] = ACTIONS(64),
    [sym_number] = ACTIONS(46),
    [sym_string] = ACTIONS(46),
    [sym_multiline_string] = ACTIONS(46),
    [sym_fstring] = ACTIONS(46),
    [anon_sym_EQ_EQ] = ACTIONS(67),
    [anon_sym_BANG_EQ] = ACTIONS(67),
    [anon_sym_LT_EQ] = ACTIONS(67),
    [anon_sym_GT_EQ] = ACTIONS(67),
    [anon_sym_DOT_DOT] = ACTIONS(67),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym_SLASH_SLASH] = ACTIONS(67),
    [anon_sym_EQ] = ACTIONS(70),
    [anon_sym_LT] = ACTIONS(70),
    [anon_sym_GT] = ACTIONS(70),
    [anon_sym_PLUS] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(70),
    [anon_sym_PERCENT] = ACTIONS(67),
    [anon_sym_POUND] = ACTIONS(67),
    [anon_sym_QMARK] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(76),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_SEMI] = ACTIONS(79),
    [anon_sym_COLON] = ACTIONS(79),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(87),
    [sym_comment] = ACTIONS(85),
    [anon_sym_if] = ACTIONS(87),
    [anon_sym_elif] = ACTIONS(87),
    [anon_sym_else] = ACTIONS(87),
    [anon_sym_while] = ACTIONS(87),
    [anon_sym_for] = ACTIONS(87),
    [anon_sym_in] = ACTIONS(87),
    [anon_sym_break] = ACTIONS(87),
    [anon_sym_continue] = ACTIONS(87),
    [anon_sym_with] = ACTIONS(87),
    [anon_sym_as] = ACTIONS(87),
    [anon_sym_try] = ACTIONS(87),
    [anon_sym_except] = ACTIONS(87),
    [anon_sym_finally] = ACTIONS(87),
    [anon_sym_local] = ACTIONS(87),
    [anon_sym_global] = ACTIONS(87),
    [anon_sym_import] = ACTIONS(87),
    [anon_sym_from] = ACTIONS(87),
    [anon_sym_fn] = ACTIONS(87),
    [anon_sym_return] = ACTIONS(87),
    [anon_sym_del] = ACTIONS(87),
    [sym_keyword_exception] = ACTIONS(87),
    [anon_sym_and] = ACTIONS(87),
    [anon_sym_or] = ACTIONS(87),
    [anon_sym_not] = ACTIONS(87),
    [anon_sym_has] = ACTIONS(87),
    [anon_sym_print] = ACTIONS(87),
    [anon_sym_gc] = ACTIONS(87),
    [sym_decorator] = ACTIONS(85),
    [anon_sym_true] = ACTIONS(87),
    [anon_sym_false] = ACTIONS(87),
    [sym_nil] = ACTIONS(87),
    [anon_sym_setmetatable] = ACTIONS(87),
    [anon_sym_getmetatable] = ACTIONS(87),
    [anon_sym_str] = ACTIONS(87),
    [anon_sym_len] = ACTIONS(87),
    [anon_sym_type] = ACTIONS(87),
    [anon_sym_assert] = ACTIONS(87),
    [anon_sym_error] = ACTIONS(87),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [sym_multiline_string] = ACTIONS(85),
    [sym_fstring] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(85),
    [anon_sym_BANG_EQ] = ACTIONS(85),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_DOT_DOT] = ACTIONS(85),
    [anon_sym_STAR_STAR] = ACTIONS(85),
    [anon_sym_SLASH_SLASH] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(87),
    [anon_sym_GT] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(87),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PERCENT] = ACTIONS(85),
    [anon_sym_POUND] = ACTIONS(85),
    [anon_sym_QMARK] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_DOT] = ACTIONS(87),
    [anon_sym_SEMI] = ACTIONS(85),
    [anon_sym_COLON] = ACTIONS(85),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_identifier] = ACTIONS(91),
    [sym_comment] = ACTIONS(89),
    [anon_sym_if] = ACTIONS(91),
    [anon_sym_elif] = ACTIONS(91),
    [anon_sym_else] = ACTIONS(91),
    [anon_sym_while] = ACTIONS(91),
    [anon_sym_for] = ACTIONS(91),
    [anon_sym_in] = ACTIONS(91),
    [anon_sym_break] = ACTIONS(91),
    [anon_sym_continue] = ACTIONS(91),
    [anon_sym_with] = ACTIONS(91),
    [anon_sym_as] = ACTIONS(91),
    [anon_sym_try] = ACTIONS(91),
    [anon_sym_except] = ACTIONS(91),
    [anon_sym_finally] = ACTIONS(91),
    [anon_sym_local] = ACTIONS(91),
    [anon_sym_global] = ACTIONS(91),
    [anon_sym_import] = ACTIONS(91),
    [anon_sym_from] = ACTIONS(91),
    [anon_sym_fn] = ACTIONS(91),
    [anon_sym_return] = ACTIONS(91),
    [anon_sym_del] = ACTIONS(91),
    [sym_keyword_exception] = ACTIONS(91),
    [anon_sym_and] = ACTIONS(91),
    [anon_sym_or] = ACTIONS(91),
    [anon_sym_not] = ACTIONS(91),
    [anon_sym_has] = ACTIONS(91),
    [anon_sym_print] = ACTIONS(91),
    [anon_sym_gc] = ACTIONS(91),
    [sym_decorator] = ACTIONS(89),
    [anon_sym_true] = ACTIONS(91),
    [anon_sym_false] = ACTIONS(91),
    [sym_nil] = ACTIONS(91),
    [anon_sym_setmetatable] = ACTIONS(91),
    [anon_sym_getmetatable] = ACTIONS(91),
    [anon_sym_str] = ACTIONS(91),
    [anon_sym_len] = ACTIONS(91),
    [anon_sym_type] = ACTIONS(91),
    [anon_sym_assert] = ACTIONS(91),
    [anon_sym_error] = ACTIONS(91),
    [sym_number] = ACTIONS(89),
    [sym_string] = ACTIONS(89),
    [sym_multiline_string] = ACTIONS(89),
    [sym_fstring] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_BANG_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_STAR_STAR] = ACTIONS(89),
    [anon_sym_SLASH_SLASH] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(91),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_PERCENT] = ACTIONS(89),
    [anon_sym_POUND] = ACTIONS(89),
    [anon_sym_QMARK] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(91),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(91),
    [anon_sym_SEMI] = ACTIONS(89),
    [anon_sym_COLON] = ACTIONS(89),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_identifier] = ACTIONS(95),
    [sym_comment] = ACTIONS(93),
    [anon_sym_if] = ACTIONS(95),
    [anon_sym_elif] = ACTIONS(95),
    [anon_sym_else] = ACTIONS(95),
    [anon_sym_while] = ACTIONS(95),
    [anon_sym_for] = ACTIONS(95),
    [anon_sym_in] = ACTIONS(95),
    [anon_sym_break] = ACTIONS(95),
    [anon_sym_continue] = ACTIONS(95),
    [anon_sym_with] = ACTIONS(95),
    [anon_sym_as] = ACTIONS(95),
    [anon_sym_try] = ACTIONS(95),
    [anon_sym_except] = ACTIONS(95),
    [anon_sym_finally] = ACTIONS(95),
    [anon_sym_local] = ACTIONS(95),
    [anon_sym_global] = ACTIONS(95),
    [anon_sym_import] = ACTIONS(95),
    [anon_sym_from] = ACTIONS(95),
    [anon_sym_fn] = ACTIONS(95),
    [anon_sym_return] = ACTIONS(95),
    [anon_sym_del] = ACTIONS(95),
    [sym_keyword_exception] = ACTIONS(95),
    [anon_sym_and] = ACTIONS(95),
    [anon_sym_or] = ACTIONS(95),
    [anon_sym_not] = ACTIONS(95),
    [anon_sym_has] = ACTIONS(95),
    [anon_sym_print] = ACTIONS(95),
    [anon_sym_gc] = ACTIONS(95),
    [sym_decorator] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(95),
    [anon_sym_false] = ACTIONS(95),
    [sym_nil] = ACTIONS(95),
    [anon_sym_setmetatable] = ACTIONS(95),
    [anon_sym_getmetatable] = ACTIONS(95),
    [anon_sym_str] = ACTIONS(95),
    [anon_sym_len] = ACTIONS(95),
    [anon_sym_type] = ACTIONS(95),
    [anon_sym_assert] = ACTIONS(95),
    [anon_sym_error] = ACTIONS(95),
    [sym_number] = ACTIONS(93),
    [sym_string] = ACTIONS(93),
    [sym_multiline_string] = ACTIONS(93),
    [sym_fstring] = ACTIONS(93),
    [anon_sym_EQ_EQ] = ACTIONS(93),
    [anon_sym_BANG_EQ] = ACTIONS(93),
    [anon_sym_LT_EQ] = ACTIONS(93),
    [anon_sym_GT_EQ] = ACTIONS(93),
    [anon_sym_DOT_DOT] = ACTIONS(93),
    [anon_sym_STAR_STAR] = ACTIONS(93),
    [anon_sym_SLASH_SLASH] = ACTIONS(93),
    [anon_sym_EQ] = ACTIONS(95),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_GT] = ACTIONS(95),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_DASH] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(95),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_PERCENT] = ACTIONS(93),
    [anon_sym_POUND] = ACTIONS(93),
    [anon_sym_QMARK] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(95),
    [anon_sym_RBRACK] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(93),
    [anon_sym_DOT] = ACTIONS(95),
    [anon_sym_SEMI] = ACTIONS(93),
    [anon_sym_COLON] = ACTIONS(93),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_identifier] = ACTIONS(99),
    [sym_comment] = ACTIONS(97),
    [anon_sym_if] = ACTIONS(99),
    [anon_sym_elif] = ACTIONS(99),
    [anon_sym_else] = ACTIONS(99),
    [anon_sym_while] = ACTIONS(99),
    [anon_sym_for] = ACTIONS(99),
    [anon_sym_in] = ACTIONS(99),
    [anon_sym_break] = ACTIONS(99),
    [anon_sym_continue] = ACTIONS(99),
    [anon_sym_with] = ACTIONS(99),
    [anon_sym_as] = ACTIONS(99),
    [anon_sym_try] = ACTIONS(99),
    [anon_sym_except] = ACTIONS(99),
    [anon_sym_finally] = ACTIONS(99),
    [anon_sym_local] = ACTIONS(99),
    [anon_sym_global] = ACTIONS(99),
    [anon_sym_import] = ACTIONS(99),
    [anon_sym_from] = ACTIONS(99),
    [anon_sym_fn] = ACTIONS(99),
    [anon_sym_return] = ACTIONS(99),
    [anon_sym_del] = ACTIONS(99),
    [sym_keyword_exception] = ACTIONS(99),
    [anon_sym_and] = ACTIONS(99),
    [anon_sym_or] = ACTIONS(99),
    [anon_sym_not] = ACTIONS(99),
    [anon_sym_has] = ACTIONS(99),
    [anon_sym_print] = ACTIONS(99),
    [anon_sym_gc] = ACTIONS(99),
    [sym_decorator] = ACTIONS(97),
    [anon_sym_true] = ACTIONS(99),
    [anon_sym_false] = ACTIONS(99),
    [sym_nil] = ACTIONS(99),
    [anon_sym_setmetatable] = ACTIONS(99),
    [anon_sym_getmetatable] = ACTIONS(99),
    [anon_sym_str] = ACTIONS(99),
    [anon_sym_len] = ACTIONS(99),
    [anon_sym_type] = ACTIONS(99),
    [anon_sym_assert] = ACTIONS(99),
    [anon_sym_error] = ACTIONS(99),
    [sym_number] = ACTIONS(97),
    [sym_string] = ACTIONS(97),
    [sym_multiline_string] = ACTIONS(97),
    [sym_fstring] = ACTIONS(97),
    [anon_sym_EQ_EQ] = ACTIONS(97),
    [anon_sym_BANG_EQ] = ACTIONS(97),
    [anon_sym_LT_EQ] = ACTIONS(97),
    [anon_sym_GT_EQ] = ACTIONS(97),
    [anon_sym_DOT_DOT] = ACTIONS(97),
    [anon_sym_STAR_STAR] = ACTIONS(97),
    [anon_sym_SLASH_SLASH] = ACTIONS(97),
    [anon_sym_EQ] = ACTIONS(99),
    [anon_sym_LT] = ACTIONS(99),
    [anon_sym_GT] = ACTIONS(99),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(99),
    [anon_sym_STAR] = ACTIONS(99),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_PERCENT] = ACTIONS(97),
    [anon_sym_POUND] = ACTIONS(97),
    [anon_sym_QMARK] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_RPAREN] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_RBRACK] = ACTIONS(97),
    [anon_sym_COMMA] = ACTIONS(97),
    [anon_sym_DOT] = ACTIONS(99),
    [anon_sym_SEMI] = ACTIONS(97),
    [anon_sym_COLON] = ACTIONS(97),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_identifier] = ACTIONS(103),
    [sym_comment] = ACTIONS(101),
    [anon_sym_if] = ACTIONS(103),
    [anon_sym_elif] = ACTIONS(103),
    [anon_sym_else] = ACTIONS(103),
    [anon_sym_while] = ACTIONS(103),
    [anon_sym_for] = ACTIONS(103),
    [anon_sym_in] = ACTIONS(103),
    [anon_sym_break] = ACTIONS(103),
    [anon_sym_continue] = ACTIONS(103),
    [anon_sym_with] = ACTIONS(103),
    [anon_sym_as] = ACTIONS(103),
    [anon_sym_try] = ACTIONS(103),
    [anon_sym_except] = ACTIONS(103),
    [anon_sym_finally] = ACTIONS(103),
    [anon_sym_local] = ACTIONS(103),
    [anon_sym_global] = ACTIONS(103),
    [anon_sym_import] = ACTIONS(103),
    [anon_sym_from] = ACTIONS(103),
    [anon_sym_fn] = ACTIONS(103),
    [anon_sym_return] = ACTIONS(103),
    [anon_sym_del] = ACTIONS(103),
    [sym_keyword_exception] = ACTIONS(103),
    [anon_sym_and] = ACTIONS(103),
    [anon_sym_or] = ACTIONS(103),
    [anon_sym_not] = ACTIONS(103),
    [anon_sym_has] = ACTIONS(103),
    [anon_sym_print] = ACTIONS(103),
    [anon_sym_gc] = ACTIONS(103),
    [sym_decorator] = ACTIONS(101),
    [anon_sym_true] = ACTIONS(103),
    [anon_sym_false] = ACTIONS(103),
    [sym_nil] = ACTIONS(103),
    [anon_sym_setmetatable] = ACTIONS(103),
    [anon_sym_getmetatable] = ACTIONS(103),
    [anon_sym_str] = ACTIONS(103),
    [anon_sym_len] = ACTIONS(103),
    [anon_sym_type] = ACTIONS(103),
    [anon_sym_assert] = ACTIONS(103),
    [anon_sym_error] = ACTIONS(103),
    [sym_number] = ACTIONS(101),
    [sym_string] = ACTIONS(101),
    [sym_multiline_string] = ACTIONS(101),
    [sym_fstring] = ACTIONS(101),
    [anon_sym_EQ_EQ] = ACTIONS(101),
    [anon_sym_BANG_EQ] = ACTIONS(101),
    [anon_sym_LT_EQ] = ACTIONS(101),
    [anon_sym_GT_EQ] = ACTIONS(101),
    [anon_sym_DOT_DOT] = ACTIONS(101),
    [anon_sym_STAR_STAR] = ACTIONS(101),
    [anon_sym_SLASH_SLASH] = ACTIONS(101),
    [anon_sym_EQ] = ACTIONS(103),
    [anon_sym_LT] = ACTIONS(103),
    [anon_sym_GT] = ACTIONS(103),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(103),
    [anon_sym_STAR] = ACTIONS(103),
    [anon_sym_SLASH] = ACTIONS(103),
    [anon_sym_PERCENT] = ACTIONS(101),
    [anon_sym_POUND] = ACTIONS(101),
    [anon_sym_QMARK] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(101),
    [anon_sym_RPAREN] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_COMMA] = ACTIONS(101),
    [anon_sym_DOT] = ACTIONS(103),
    [anon_sym_SEMI] = ACTIONS(101),
    [anon_sym_COLON] = ACTIONS(101),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_identifier] = ACTIONS(107),
    [sym_comment] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(107),
    [anon_sym_elif] = ACTIONS(107),
    [anon_sym_else] = ACTIONS(107),
    [anon_sym_while] = ACTIONS(107),
    [anon_sym_for] = ACTIONS(107),
    [anon_sym_in] = ACTIONS(107),
    [anon_sym_break] = ACTIONS(107),
    [anon_sym_continue] = ACTIONS(107),
    [anon_sym_with] = ACTIONS(107),
    [anon_sym_as] = ACTIONS(107),
    [anon_sym_try] = ACTIONS(107),
    [anon_sym_except] = ACTIONS(107),
    [anon_sym_finally] = ACTIONS(107),
    [anon_sym_local] = ACTIONS(107),
    [anon_sym_global] = ACTIONS(107),
    [anon_sym_import] = ACTIONS(107),
    [anon_sym_from] = ACTIONS(107),
    [anon_sym_fn] = ACTIONS(107),
    [anon_sym_return] = ACTIONS(107),
    [anon_sym_del] = ACTIONS(107),
    [sym_keyword_exception] = ACTIONS(107),
    [anon_sym_and] = ACTIONS(107),
    [anon_sym_or] = ACTIONS(107),
    [anon_sym_not] = ACTIONS(107),
    [anon_sym_has] = ACTIONS(107),
    [anon_sym_print] = ACTIONS(107),
    [anon_sym_gc] = ACTIONS(107),
    [sym_decorator] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(107),
    [anon_sym_false] = ACTIONS(107),
    [sym_nil] = ACTIONS(107),
    [anon_sym_setmetatable] = ACTIONS(107),
    [anon_sym_getmetatable] = ACTIONS(107),
    [anon_sym_str] = ACTIONS(107),
    [anon_sym_len] = ACTIONS(107),
    [anon_sym_type] = ACTIONS(107),
    [anon_sym_assert] = ACTIONS(107),
    [anon_sym_error] = ACTIONS(107),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [sym_multiline_string] = ACTIONS(105),
    [sym_fstring] = ACTIONS(105),
    [anon_sym_EQ_EQ] = ACTIONS(105),
    [anon_sym_BANG_EQ] = ACTIONS(105),
    [anon_sym_LT_EQ] = ACTIONS(105),
    [anon_sym_GT_EQ] = ACTIONS(105),
    [anon_sym_DOT_DOT] = ACTIONS(105),
    [anon_sym_STAR_STAR] = ACTIONS(105),
    [anon_sym_SLASH_SLASH] = ACTIONS(105),
    [anon_sym_EQ] = ACTIONS(107),
    [anon_sym_LT] = ACTIONS(107),
    [anon_sym_GT] = ACTIONS(107),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(107),
    [anon_sym_STAR] = ACTIONS(107),
    [anon_sym_SLASH] = ACTIONS(107),
    [anon_sym_PERCENT] = ACTIONS(105),
    [anon_sym_POUND] = ACTIONS(105),
    [anon_sym_QMARK] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_RPAREN] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_LBRACK] = ACTIONS(107),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_COMMA] = ACTIONS(105),
    [anon_sym_DOT] = ACTIONS(107),
    [anon_sym_SEMI] = ACTIONS(105),
    [anon_sym_COLON] = ACTIONS(105),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [sym_comment] = ACTIONS(109),
    [anon_sym_if] = ACTIONS(111),
    [anon_sym_elif] = ACTIONS(111),
    [anon_sym_else] = ACTIONS(111),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_for] = ACTIONS(111),
    [anon_sym_in] = ACTIONS(111),
    [anon_sym_break] = ACTIONS(111),
    [anon_sym_continue] = ACTIONS(111),
    [anon_sym_with] = ACTIONS(111),
    [anon_sym_as] = ACTIONS(111),
    [anon_sym_try] = ACTIONS(111),
    [anon_sym_except] = ACTIONS(111),
    [anon_sym_finally] = ACTIONS(111),
    [anon_sym_local] = ACTIONS(111),
    [anon_sym_global] = ACTIONS(111),
    [anon_sym_import] = ACTIONS(111),
    [anon_sym_from] = ACTIONS(111),
    [anon_sym_fn] = ACTIONS(111),
    [anon_sym_return] = ACTIONS(111),
    [anon_sym_del] = ACTIONS(111),
    [sym_keyword_exception] = ACTIONS(111),
    [anon_sym_and] = ACTIONS(111),
    [anon_sym_or] = ACTIONS(111),
    [anon_sym_not] = ACTIONS(111),
    [anon_sym_has] = ACTIONS(111),
    [anon_sym_print] = ACTIONS(111),
    [anon_sym_gc] = ACTIONS(111),
    [sym_decorator] = ACTIONS(109),
    [anon_sym_true] = ACTIONS(111),
    [anon_sym_false] = ACTIONS(111),
    [sym_nil] = ACTIONS(111),
    [anon_sym_setmetatable] = ACTIONS(111),
    [anon_sym_getmetatable] = ACTIONS(111),
    [anon_sym_str] = ACTIONS(111),
    [anon_sym_len] = ACTIONS(111),
    [anon_sym_type] = ACTIONS(111),
    [anon_sym_assert] = ACTIONS(111),
    [anon_sym_error] = ACTIONS(111),
    [sym_number] = ACTIONS(109),
    [sym_string] = ACTIONS(109),
    [sym_multiline_string] = ACTIONS(109),
    [sym_fstring] = ACTIONS(109),
    [anon_sym_EQ_EQ] = ACTIONS(109),
    [anon_sym_BANG_EQ] = ACTIONS(109),
    [anon_sym_LT_EQ] = ACTIONS(109),
    [anon_sym_GT_EQ] = ACTIONS(109),
    [anon_sym_DOT_DOT] = ACTIONS(109),
    [anon_sym_STAR_STAR] = ACTIONS(109),
    [anon_sym_SLASH_SLASH] = ACTIONS(109),
    [anon_sym_EQ] = ACTIONS(111),
    [anon_sym_LT] = ACTIONS(111),
    [anon_sym_GT] = ACTIONS(111),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym_STAR] = ACTIONS(111),
    [anon_sym_SLASH] = ACTIONS(111),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_QMARK] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_DOT] = ACTIONS(111),
    [anon_sym_SEMI] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(113),
    [sym_identifier] = ACTIONS(115),
    [sym_comment] = ACTIONS(113),
    [anon_sym_if] = ACTIONS(115),
    [anon_sym_elif] = ACTIONS(115),
    [anon_sym_else] = ACTIONS(115),
    [anon_sym_while] = ACTIONS(115),
    [anon_sym_for] = ACTIONS(115),
    [anon_sym_in] = ACTIONS(115),
    [anon_sym_break] = ACTIONS(115),
    [anon_sym_continue] = ACTIONS(115),
    [anon_sym_with] = ACTIONS(115),
    [anon_sym_as] = ACTIONS(115),
    [anon_sym_try] = ACTIONS(115),
    [anon_sym_except] = ACTIONS(115),
    [anon_sym_finally] = ACTIONS(115),
    [anon_sym_local] = ACTIONS(115),
    [anon_sym_global] = ACTIONS(115),
    [anon_sym_import] = ACTIONS(115),
    [anon_sym_from] = ACTIONS(115),
    [anon_sym_fn] = ACTIONS(115),
    [anon_sym_return] = ACTIONS(115),
    [anon_sym_del] = ACTIONS(115),
    [sym_keyword_exception] = ACTIONS(115),
    [anon_sym_and] = ACTIONS(115),
    [anon_sym_or] = ACTIONS(115),
    [anon_sym_not] = ACTIONS(115),
    [anon_sym_has] = ACTIONS(115),
    [anon_sym_print] = ACTIONS(115),
    [anon_sym_gc] = ACTIONS(115),
    [sym_decorator] = ACTIONS(113),
    [anon_sym_true] = ACTIONS(115),
    [anon_sym_false] = ACTIONS(115),
    [sym_nil] = ACTIONS(115),
    [anon_sym_setmetatable] = ACTIONS(115),
    [anon_sym_getmetatable] = ACTIONS(115),
    [anon_sym_str] = ACTIONS(115),
    [anon_sym_len] = ACTIONS(115),
    [anon_sym_type] = ACTIONS(115),
    [anon_sym_assert] = ACTIONS(115),
    [anon_sym_error] = ACTIONS(115),
    [sym_number] = ACTIONS(113),
    [sym_string] = ACTIONS(113),
    [sym_multiline_string] = ACTIONS(113),
    [sym_fstring] = ACTIONS(113),
    [anon_sym_EQ_EQ] = ACTIONS(113),
    [anon_sym_BANG_EQ] = ACTIONS(113),
    [anon_sym_LT_EQ] = ACTIONS(113),
    [anon_sym_GT_EQ] = ACTIONS(113),
    [anon_sym_DOT_DOT] = ACTIONS(113),
    [anon_sym_STAR_STAR] = ACTIONS(113),
    [anon_sym_SLASH_SLASH] = ACTIONS(113),
    [anon_sym_EQ] = ACTIONS(115),
    [anon_sym_LT] = ACTIONS(115),
    [anon_sym_GT] = ACTIONS(115),
    [anon_sym_PLUS] = ACTIONS(113),
    [anon_sym_DASH] = ACTIONS(115),
    [anon_sym_STAR] = ACTIONS(115),
    [anon_sym_SLASH] = ACTIONS(115),
    [anon_sym_PERCENT] = ACTIONS(113),
    [anon_sym_POUND] = ACTIONS(113),
    [anon_sym_QMARK] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_RPAREN] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(113),
    [anon_sym_RBRACE] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(115),
    [anon_sym_RBRACK] = ACTIONS(113),
    [anon_sym_COMMA] = ACTIONS(113),
    [anon_sym_DOT] = ACTIONS(115),
    [anon_sym_SEMI] = ACTIONS(113),
    [anon_sym_COLON] = ACTIONS(113),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(117),
    [sym_identifier] = ACTIONS(119),
    [sym_comment] = ACTIONS(117),
    [anon_sym_if] = ACTIONS(119),
    [anon_sym_elif] = ACTIONS(119),
    [anon_sym_else] = ACTIONS(119),
    [anon_sym_while] = ACTIONS(119),
    [anon_sym_for] = ACTIONS(119),
    [anon_sym_in] = ACTIONS(119),
    [anon_sym_break] = ACTIONS(119),
    [anon_sym_continue] = ACTIONS(119),
    [anon_sym_with] = ACTIONS(119),
    [anon_sym_as] = ACTIONS(119),
    [anon_sym_try] = ACTIONS(119),
    [anon_sym_except] = ACTIONS(119),
    [anon_sym_finally] = ACTIONS(119),
    [anon_sym_local] = ACTIONS(119),
    [anon_sym_global] = ACTIONS(119),
    [anon_sym_import] = ACTIONS(119),
    [anon_sym_from] = ACTIONS(119),
    [anon_sym_fn] = ACTIONS(119),
    [anon_sym_return] = ACTIONS(119),
    [anon_sym_del] = ACTIONS(119),
    [sym_keyword_exception] = ACTIONS(119),
    [anon_sym_and] = ACTIONS(119),
    [anon_sym_or] = ACTIONS(119),
    [anon_sym_not] = ACTIONS(119),
    [anon_sym_has] = ACTIONS(119),
    [anon_sym_print] = ACTIONS(119),
    [anon_sym_gc] = ACTIONS(119),
    [sym_decorator] = ACTIONS(117),
    [anon_sym_true] = ACTIONS(119),
    [anon_sym_false] = ACTIONS(119),
    [sym_nil] = ACTIONS(119),
    [anon_sym_setmetatable] = ACTIONS(119),
    [anon_sym_getmetatable] = ACTIONS(119),
    [anon_sym_str] = ACTIONS(119),
    [anon_sym_len] = ACTIONS(119),
    [anon_sym_type] = ACTIONS(119),
    [anon_sym_assert] = ACTIONS(119),
    [anon_sym_error] = ACTIONS(119),
    [sym_number] = ACTIONS(117),
    [sym_string] = ACTIONS(117),
    [sym_multiline_string] = ACTIONS(117),
    [sym_fstring] = ACTIONS(117),
    [anon_sym_EQ_EQ] = ACTIONS(117),
    [anon_sym_BANG_EQ] = ACTIONS(117),
    [anon_sym_LT_EQ] = ACTIONS(117),
    [anon_sym_GT_EQ] = ACTIONS(117),
    [anon_sym_DOT_DOT] = ACTIONS(117),
    [anon_sym_STAR_STAR] = ACTIONS(117),
    [anon_sym_SLASH_SLASH] = ACTIONS(117),
    [anon_sym_EQ] = ACTIONS(119),
    [anon_sym_LT] = ACTIONS(119),
    [anon_sym_GT] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(117),
    [anon_sym_DASH] = ACTIONS(119),
    [anon_sym_STAR] = ACTIONS(119),
    [anon_sym_SLASH] = ACTIONS(119),
    [anon_sym_PERCENT] = ACTIONS(117),
    [anon_sym_POUND] = ACTIONS(117),
    [anon_sym_QMARK] = ACTIONS(117),
    [anon_sym_LPAREN] = ACTIONS(117),
    [anon_sym_RPAREN] = ACTIONS(117),
    [anon_sym_LBRACE] = ACTIONS(117),
    [anon_sym_RBRACE] = ACTIONS(117),
    [anon_sym_LBRACK] = ACTIONS(119),
    [anon_sym_RBRACK] = ACTIONS(117),
    [anon_sym_COMMA] = ACTIONS(117),
    [anon_sym_DOT] = ACTIONS(119),
    [anon_sym_SEMI] = ACTIONS(117),
    [anon_sym_COLON] = ACTIONS(117),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_control, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_control, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_declaration, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_declaration, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_operator, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_operator, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_other, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_other, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation_bracket, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation_bracket, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation_delimiter, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation_delimiter, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pua(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
