#ifndef TOKEN_H
#define TOKEN_H

typedef enum {
    TOKEN_EOF,
    TOKEN_ERROR,
    
    // Single-character tokens
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_DOT_DOT, TOKEN_MINUS, TOKEN_PLUS,
    TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,
    TOKEN_EQUALS, TOKEN_HASH, TOKEN_QUESTION, TOKEN_COLON,
    TOKEN_AT,
    TOKEN_POWER, TOKEN_INT_DIV, TOKEN_PERCENT,
    TOKEN_EQUAL_EQUAL, TOKEN_BANG_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_INDENT, TOKEN_DEDENT,

    // Literals
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_FSTRING, TOKEN_NUMBER,
    TOKEN_NIL, TOKEN_TRUE, TOKEN_FALSE,

    // Keywords
    TOKEN_PRINT,
    TOKEN_LOCAL,
    TOKEN_FN,
    TOKEN_RETURN,
    TOKEN_IF,
    TOKEN_ELIF,
    TOKEN_ELSE,
    TOKEN_WHILE,
    TOKEN_FOR,
    TOKEN_IN,
    TOKEN_HAS,
    TOKEN_GLOBAL,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_NOT,
    TOKEN_WITH,
    TOKEN_AS,
    TOKEN_TRY,
    TOKEN_EXCEPT,
    TOKEN_FINALLY,
    TOKEN_THROW,
    TOKEN_GC,
    TOKEN_IMPORT,
    TOKEN_FROM,
    TOKEN_DEL
} TokenType;

typedef struct {
    TokenType type;
    const char* start;
    int length;
    int line;
} Token;

#endif
